#! /usr/bin/env python3
# coding: utf-8

"""
This fast installer is destined to the developpers who want to create
their own quick installer, in the 'geninstaller' way.
Just complete the informations asked below, the magic will do the rest.
"""

import os
import pkg_resources
dependencies = [
    'flamewok>=1.0.7',  # to replace with geninstaller instead
]
clean_up = False
try:
    pkg_resources.require(dependencies)
except pkg_resources.DistributionNotFound:
    os.system('pip install --upgrade flamewok')  # to replace with geninstaller
    clean_up = True
from flamewok.cli import cli
from flamewok.helpers import clear
from geninstaller import core


# PLACE THIS FILE IN THE ROOT DIRECTORY OF YOUR PROJECT

# =====================================================================
# ======= Complete this informations ==================================

# choose a good name, do NOT use underscores here
NAME = "fake application"
# short description (optionnal), a few words would be fine
DESCRIPTION = "A fake application for testing"
# The main executable file of the application
# path relative to this directory (BASE_DIR defined below)
EXECUTABLE = "fake/fake.py"
# The icon that your system will use (optionnal, but so much better)
# path relative to this direcotry (BASE_DIR defined below)
ICON = "fake/icon.png"
# Does your application needs to appear within a terminal ?
# (usually, a graphical application doesn't need a terminal)
TERMINAL = False

# uncomment the categories in which you want your app to appear in,
# (you can add your own ones if you know how it works with gnome.)
CATEGORIES = [
    # "AudioVideo",
    # "Audio",
    "Video",
    # "Development",
    # "Education",
    # "Game",
    # "Graphics",
    "Network",
    # "Office",
    # "Settings",
    # "Utility",
]

# = do not touch what is following unless you know what you're doing ==
# =====================================================================

BASE_DIR = os.path.abspath(os.path.dirname(__file__))

datas = {
    "name": NAME,
    "exec": EXECUTABLE,
    "comment": DESCRIPTION,
    "terminal": TERMINAL,
    "icon": ICON,
    "categories": CATEGORIES,
    "base_dir": BASE_DIR,
}


def install():
    """installs geninstaller's database on the system,
     if not already installed. Absolutely required !"""
    core.autoinstall()
    # and then installs your application
    core.install(datas)


infos = (
    "ABOUT GENINSTALLER\n"
    "| This installer works with geninstaller. \n"
    "| To know more about geninstaller and its options, type in console: \n"
    "|      $ geninstaller -h"
)

if __name__ == "__main__":
    if clean_up:
        clear()

    routes = [
        f"installer program for: {NAME}",
        "INSTALLATION",
        ("", install, (
            f"Install '{NAME}' by simply executing '$ ./installer'"
            )),

        "HELP",
        ("-h", cli.help, "\n|    display this help"),
        ("--help", cli.help, "\n|    display this help"),
        infos,
    ]

    cli.route(*routes)
